apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: myproject
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
  selector:
    app: kibana
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: myproject
spec:
  ingressClassName: nginx
  rules:
  - host: kibana.p1
    http:
      paths:
      - backend:
          service:
            name: kibana
            port: 
              number: 5601
        path: /
        pathType: Prefix
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: myproject
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.10.2
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
        ports:
        - containerPort: 5601