apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: alerting
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Source topic
      - resource:
          type: topic
          name: logs
        operation: Read
      # Group used by the Kafka Streams app
      - resource:
          type: group
          name: alerting
        operation: Read
      # Target topic
      - resource:
          type: topic
          name: alerts
        operation: Write
      # Streams topics
      - resource:
          type: topic
          name: alerting-
          patternType: prefix
        operation: Write
      - resource:
          type: topic
          name: alerting-
          patternType: prefix
        operation: Read
      - resource:
          type: topic
          name: alerting-
          patternType: prefix
        operation: Create
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alerting
  name: alerting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerting
  template:
    metadata:
      labels:
        app: alerting
    spec:
      containers:
        - name: alerting
          image: ghcr.io/scholzj/building-cloud-native-logging-pipelines-on-top-of-apache-kafka:alerting
          env:
            - name: QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9093
            - name: QUARKUS_KAFKA_STREAMS_APPLICATION_ID
              value: alerting
            - name: QUARKUS_KAFKA_STREAMS_SECURITY_PROTOCOL
              value: SSL
            - name: QUARKUS_KAFKA_STREAMS_SSL_TRUSTSTORE_TYPE
              value: PKCS12
            - name: QUARKUS_KAFKA_STREAMS_SSL_TRUSTSTORE_LOCATION
              value: /etc/truststore/ca.p12
            - name: QUARKUS_KAFKA_STREAMS_SSL_TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-cluster-cluster-ca-cert
                  key: ca.password
            - name: QUARKUS_KAFKA_STREAMS_SSL_KEYSTORE_TYPE
              value: PKCS12
            - name: QUARKUS_KAFKA_STREAMS_SSL_KEYSTORE_LOCATION
              value: /etc/keystore/user.p12
            - name: QUARKUS_KAFKA_STREAMS_SSL_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alerting
                  key: user.password
          volumeMounts:
            - name: truststore
              mountPath: "/etc/truststore"
              readOnly: true
            - name: keystore
              mountPath: "/etc/keystore"
              readOnly: true
      volumes:
        - name: truststore
          secret:
            secretName: my-cluster-cluster-ca-cert
            items:
              - key: ca.p12
                path: ca.p12
        - name: keystore
          secret:
            secretName: alerting
            items:
              - key: user.p12
                path: user.p12
---
